[package]
name    = "glum"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium      = "0.33.0"
hotwatch   = "0.5.0"
egui_glium = "0.23.0"
winit      = "0.28"
egui       = "0.23.0"
